/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * Language Translator
 * Language Translator translates text from one language to another. The service offers multiple domain-specific models that you can customize based on your unique terminology and language. Use Language Translator to take news from across the globe and present it in your language, communicate with your customers in their own language, and more.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * Response payload for models.
 */
@ApiModel(description = "Response payload for models.")
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-10-03T18:29:51.729+05:30")
public class TranslationModel   {
  @JsonProperty("model_id")
  private String modelId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("source")
  private String source = null;

  @JsonProperty("target")
  private String target = null;

  @JsonProperty("base_model_id")
  private String baseModelId = null;

  @JsonProperty("domain")
  private String domain = null;

  @JsonProperty("customizable")
  private Boolean customizable = null;

  @JsonProperty("default_model")
  private Boolean defaultModel = null;

  @JsonProperty("owner")
  private String owner = null;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
   * Availability of a model.
   */
  public enum StatusEnum {
    UPLOADING("uploading"),
    
    UPLOADED("uploaded"),
    
    DISPATCHING("dispatching"),
    
    QUEUED("queued"),
    
    TRAINING("training"),
    
    TRAINED("trained"),
    
    PUBLISHING("publishing"),
    
    AVAILABLE("available"),
    
    DELETED("deleted"),
    
    ERROR("error");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  public TranslationModel modelId(String modelId) {
    this.modelId = modelId;
    return this;
  }

   /**
   * A globally unique string that identifies the underlying model that is used for translation. This string contains all the information about source language, target language, domain, and various other related configurations.
   * @return modelId
  **/
  @JsonProperty("model_id")
  @ApiModelProperty(required = true, value = "A globally unique string that identifies the underlying model that is used for translation. This string contains all the information about source language, target language, domain, and various other related configurations.")
  @NotNull
  public String getModelId() {
    return modelId;
  }

  public void setModelId(String modelId) {
    this.modelId = modelId;
  }

  public TranslationModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * If a model is trained by a user, there might be an optional â€œnameâ€ parameter attached during training to help the user identify the model.
   * @return name
  **/
  @JsonProperty("name")
  @ApiModelProperty(value = "If a model is trained by a user, there might be an optional â€œnameâ€ parameter attached during training to help the user identify the model.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TranslationModel source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Source language in two letter language code. Use the five letter code when clarifying between multiple supported languages. When model_id is used directly, it will override the source-target language combination. Also, when a two letter language code is used, but no suitable default is found, it returns an error.
   * @return source
  **/
  @JsonProperty("source")
  @ApiModelProperty(value = "Source language in two letter language code. Use the five letter code when clarifying between multiple supported languages. When model_id is used directly, it will override the source-target language combination. Also, when a two letter language code is used, but no suitable default is found, it returns an error.")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public TranslationModel target(String target) {
    this.target = target;
    return this;
  }

   /**
   * Target language in two letter language code.
   * @return target
  **/
  @JsonProperty("target")
  @ApiModelProperty(value = "Target language in two letter language code.")
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }

  public TranslationModel baseModelId(String baseModelId) {
    this.baseModelId = baseModelId;
    return this;
  }

   /**
   * If this model is a custom model, this returns the base model that it is trained on. For a base model, this response value is empty.
   * @return baseModelId
  **/
  @JsonProperty("base_model_id")
  @ApiModelProperty(value = "If this model is a custom model, this returns the base model that it is trained on. For a base model, this response value is empty.")
  public String getBaseModelId() {
    return baseModelId;
  }

  public void setBaseModelId(String baseModelId) {
    this.baseModelId = baseModelId;
  }

  public TranslationModel domain(String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * The domain of the translation model.
   * @return domain
  **/
  @JsonProperty("domain")
  @ApiModelProperty(value = "The domain of the translation model.")
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }

  public TranslationModel customizable(Boolean customizable) {
    this.customizable = customizable;
    return this;
  }

   /**
   * Whether this model can be used as a base for customization. Customized models are not further customizable, and we don't allow the customization of certain base models.
   * @return customizable
  **/
  @JsonProperty("customizable")
  @ApiModelProperty(value = "Whether this model can be used as a base for customization. Customized models are not further customizable, and we don't allow the customization of certain base models.")
  public Boolean getCustomizable() {
    return customizable;
  }

  public void setCustomizable(Boolean customizable) {
    this.customizable = customizable;
  }

  public TranslationModel defaultModel(Boolean defaultModel) {
    this.defaultModel = defaultModel;
    return this;
  }

   /**
   * Whether this model is considered a default model and is used when the source and target languages are specified without the model_id.
   * @return defaultModel
  **/
  @JsonProperty("default_model")
  @ApiModelProperty(value = "Whether this model is considered a default model and is used when the source and target languages are specified without the model_id.")
  public Boolean getDefaultModel() {
    return defaultModel;
  }

  public void setDefaultModel(Boolean defaultModel) {
    this.defaultModel = defaultModel;
  }

  public TranslationModel owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Returns the Bluemix ID of the instance that created the model, or an empty string if it is a model that is trained by IBM.
   * @return owner
  **/
  @JsonProperty("owner")
  @ApiModelProperty(value = "Returns the Bluemix ID of the instance that created the model, or an empty string if it is a model that is trained by IBM.")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public TranslationModel status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Availability of a model.
   * @return status
  **/
  @JsonProperty("status")
  @ApiModelProperty(value = "Availability of a model.")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslationModel translationModel = (TranslationModel) o;
    return Objects.equals(this.modelId, translationModel.modelId) &&
        Objects.equals(this.name, translationModel.name) &&
        Objects.equals(this.source, translationModel.source) &&
        Objects.equals(this.target, translationModel.target) &&
        Objects.equals(this.baseModelId, translationModel.baseModelId) &&
        Objects.equals(this.domain, translationModel.domain) &&
        Objects.equals(this.customizable, translationModel.customizable) &&
        Objects.equals(this.defaultModel, translationModel.defaultModel) &&
        Objects.equals(this.owner, translationModel.owner) &&
        Objects.equals(this.status, translationModel.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelId, name, source, target, baseModelId, domain, customizable, defaultModel, owner, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslationModel {\n");
    
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    baseModelId: ").append(toIndentedString(baseModelId)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    customizable: ").append(toIndentedString(customizable)).append("\n");
    sb.append("    defaultModel: ").append(toIndentedString(defaultModel)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

