/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * Language Translator
 * Language Translator translates text from one language to another. The service offers multiple domain-specific models that you can customize based on your unique terminology and language. Use Language Translator to take news from across the globe and present it in your language, communicate with your customers in their own language, and more.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.Translation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * TranslationResult
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-10-03T18:29:51.729+05:30")
public class TranslationResult   {
  @JsonProperty("word_count")
  private Integer wordCount = null;

  @JsonProperty("character_count")
  private Integer characterCount = null;

  @JsonProperty("translations")
  private List<Translation> translations = new ArrayList<Translation>();

  public TranslationResult wordCount(Integer wordCount) {
    this.wordCount = wordCount;
    return this;
  }

   /**
   * Number of words of the complete input text.
   * @return wordCount
  **/
  @JsonProperty("word_count")
  @ApiModelProperty(required = true, value = "Number of words of the complete input text.")
  @NotNull
  public Integer getWordCount() {
    return wordCount;
  }

  public void setWordCount(Integer wordCount) {
    this.wordCount = wordCount;
  }

  public TranslationResult characterCount(Integer characterCount) {
    this.characterCount = characterCount;
    return this;
  }

   /**
   * Number of characters of the complete input text.
   * @return characterCount
  **/
  @JsonProperty("character_count")
  @ApiModelProperty(required = true, value = "Number of characters of the complete input text.")
  @NotNull
  public Integer getCharacterCount() {
    return characterCount;
  }

  public void setCharacterCount(Integer characterCount) {
    this.characterCount = characterCount;
  }

  public TranslationResult translations(List<Translation> translations) {
    this.translations = translations;
    return this;
  }

  public TranslationResult addTranslationsItem(Translation translationsItem) {
    this.translations.add(translationsItem);
    return this;
  }

   /**
   * List of translation output in UTF-8, corresponding to the list of input text.
   * @return translations
  **/
  @JsonProperty("translations")
  @ApiModelProperty(required = true, value = "List of translation output in UTF-8, corresponding to the list of input text.")
  @NotNull
  public List<Translation> getTranslations() {
    return translations;
  }

  public void setTranslations(List<Translation> translations) {
    this.translations = translations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslationResult translationResult = (TranslationResult) o;
    return Objects.equals(this.wordCount, translationResult.wordCount) &&
        Objects.equals(this.characterCount, translationResult.characterCount) &&
        Objects.equals(this.translations, translationResult.translations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wordCount, characterCount, translations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslationResult {\n");
    
    sb.append("    wordCount: ").append(toIndentedString(wordCount)).append("\n");
    sb.append("    characterCount: ").append(toIndentedString(characterCount)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

