/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.MessageInput;
import com.ibm.mfp.adapters.sample.model.RuntimeEntity;
import com.ibm.mfp.adapters.sample.model.RuntimeIntent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * BaseMessage
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-09-04T16:39:33.075+05:30")
public class BaseMessage   {
  @JsonProperty("input")
  private MessageInput input = null;

  @JsonProperty("intents")
  private List<RuntimeIntent> intents = new ArrayList<RuntimeIntent>();

  @JsonProperty("entities")
  private List<RuntimeEntity> entities = new ArrayList<RuntimeEntity>();

  @JsonProperty("alternate_intents")
  private Boolean alternateIntents = false;

  public BaseMessage input(MessageInput input) {
    this.input = input;
    return this;
  }

   /**
   * The user input from the request.
   * @return input
  **/
  @JsonProperty("input")
  @ApiModelProperty(value = "The user input from the request.")
  public MessageInput getInput() {
    return input;
  }

  public void setInput(MessageInput input) {
    this.input = input;
  }

  public BaseMessage intents(List<RuntimeIntent> intents) {
    this.intents = intents;
    return this;
  }

  public BaseMessage addIntentsItem(RuntimeIntent intentsItem) {
    this.intents.add(intentsItem);
    return this;
  }

   /**
   * An array of intents recognized in the user input, sorted in descending order of confidence
   * @return intents
  **/
  @JsonProperty("intents")
  @ApiModelProperty(required = true, value = "An array of intents recognized in the user input, sorted in descending order of confidence")
  @NotNull
  public List<RuntimeIntent> getIntents() {
    return intents;
  }

  public void setIntents(List<RuntimeIntent> intents) {
    this.intents = intents;
  }

  public BaseMessage entities(List<RuntimeEntity> entities) {
    this.entities = entities;
    return this;
  }

  public BaseMessage addEntitiesItem(RuntimeEntity entitiesItem) {
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * An array of entities identified in the user input
   * @return entities
  **/
  @JsonProperty("entities")
  @ApiModelProperty(required = true, value = "An array of entities identified in the user input")
  @NotNull
  public List<RuntimeEntity> getEntities() {
    return entities;
  }

  public void setEntities(List<RuntimeEntity> entities) {
    this.entities = entities;
  }

  public BaseMessage alternateIntents(Boolean alternateIntents) {
    this.alternateIntents = alternateIntents;
    return this;
  }

   /**
   * Whether to return more than one intent. `true` indicates that all matching intents are returned.
   * @return alternateIntents
  **/
  @JsonProperty("alternate_intents")
  @ApiModelProperty(value = "Whether to return more than one intent. `true` indicates that all matching intents are returned.")
  public Boolean getAlternateIntents() {
    return alternateIntents;
  }

  public void setAlternateIntents(Boolean alternateIntents) {
    this.alternateIntents = alternateIntents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseMessage baseMessage = (BaseMessage) o;
    return Objects.equals(this.input, baseMessage.input) &&
        Objects.equals(this.intents, baseMessage.intents) &&
        Objects.equals(this.entities, baseMessage.entities) &&
        Objects.equals(this.alternateIntents, baseMessage.alternateIntents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, intents, entities, alternateIntents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseMessage {\n");
    
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    intents: ").append(toIndentedString(intents)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    alternateIntents: ").append(toIndentedString(alternateIntents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

