/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.LogMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * An output object that includes the response to the user, the nodes that were hit, and messages from the log.
 */
@ApiModel(description = "An output object that includes the response to the user, the nodes that were hit, and messages from the log.")
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-09-04T16:39:33.075+05:30")
public class OutputData extends HashMap<String, Object>  {
  @JsonProperty("log_messages")
  private List<LogMessage> logMessages = new ArrayList<LogMessage>();

  @JsonProperty("text")
  private List<String> text = new ArrayList<String>();

  @JsonProperty("nodes_visited")
  private List<String> nodesVisited = null;

  public OutputData logMessages(List<LogMessage> logMessages) {
    this.logMessages = logMessages;
    return this;
  }

  public OutputData addLogMessagesItem(LogMessage logMessagesItem) {
    this.logMessages.add(logMessagesItem);
    return this;
  }

   /**
   * Up to 50 messages logged with the request.
   * @return logMessages
  **/
  @JsonProperty("log_messages")
  @ApiModelProperty(required = true, value = "Up to 50 messages logged with the request.")
  @NotNull
  public List<LogMessage> getLogMessages() {
    return logMessages;
  }

  public void setLogMessages(List<LogMessage> logMessages) {
    this.logMessages = logMessages;
  }

  public OutputData text(List<String> text) {
    this.text = text;
    return this;
  }

  public OutputData addTextItem(String textItem) {
    this.text.add(textItem);
    return this;
  }

   /**
   * An array of responses to the user.
   * @return text
  **/
  @JsonProperty("text")
  @ApiModelProperty(required = true, value = "An array of responses to the user.")
  @NotNull
  public List<String> getText() {
    return text;
  }

  public void setText(List<String> text) {
    this.text = text;
  }

  public OutputData nodesVisited(List<String> nodesVisited) {
    this.nodesVisited = nodesVisited;
    return this;
  }

  public OutputData addNodesVisitedItem(String nodesVisitedItem) {
    if (this.nodesVisited == null) {
      this.nodesVisited = new ArrayList<String>();
    }
    this.nodesVisited.add(nodesVisitedItem);
    return this;
  }

   /**
   * An array of the nodes that were triggered to create the response.
   * @return nodesVisited
  **/
  @JsonProperty("nodes_visited")
  @ApiModelProperty(value = "An array of the nodes that were triggered to create the response.")
  public List<String> getNodesVisited() {
    return nodesVisited;
  }

  public void setNodesVisited(List<String> nodesVisited) {
    this.nodesVisited = nodesVisited;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputData outputData = (OutputData) o;
    return Objects.equals(this.logMessages, outputData.logMessages) &&
        Objects.equals(this.text, outputData.text) &&
        Objects.equals(this.nodesVisited, outputData.nodesVisited) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logMessages, text, nodesVisited, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    logMessages: ").append(toIndentedString(logMessages)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    nodesVisited: ").append(toIndentedString(nodesVisited)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

